name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: mise run lint

  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        tool:
          - name: cabal
            command: cabal
          - name: ghc
            command: ghc
          - name: hls
            command: haskell-language-server-wrapper
          - name: stack
            command: stack
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: [lint]
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          install: false
          experimental: true
      - run: mise plugin link --force ghcup .
      - run: mise use -g ghcup:${{ matrix.tool.name }}@latest
      - run: mise install ghcup:${{ matrix.tool.name }}@latest
      - if: runner.os == 'Windows'
        run: |
          Get-ChildItem -Recurse -Path $Env:USERPROFILE\AppData\Local\mise\installs\ghcup-${{ matrix.tool.name }}
          Get-ChildItem -Recurse -Path $Env:USERPROFILE\AppData\Local\mise\shims
          Get-ChildItem -Recurse -Path $Env:USERPROFILE\AppData\Local\mise\bin
      - run: mise exec ghcup:${{ matrix.tool.name }}@latest -- ${{ matrix.tool.command }} --version
        env: { MISE_VERBOSE: 1 }
      - run: |
          mise exec ghcup:${{ matrix.tool.name }}@latest -- ${{ runner.os == 'Windows' && 'where' || 'which' }} ${{ matrix.tool.command }}
