name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: mise run lint

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        tool:
          - name: cabal
            command: cabal
          - name: ghc
            command: ghc
          - name: hls
            command: haskell-language-server-wrapper
          - name: stack
            command: stack

    name: Test (${{ matrix.os }}, ${{ matrix.tool.name }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          path: ./plugin

      - uses: jdx/mise-action@v4
        with:
          experimental: true
          mise_toml: |
            [tools."github:haskell/ghcup-hs"]
            version = "latest"
            bin = "ghcup"

      - run: mise plugin link --force ghcup ./plugin
      - run: mise --debug use -g ghcup:${{ matrix.tool.name }}@latest
      - run: mise --debug exec ghcup:${{ matrix.tool.name }}@latest -- ${{ matrix.tool.command }} --version
      - run: |
          mise --debug exec ghcup:${{ matrix.tool.name }}@latest -- ${{ runner.os == 'Windows' && 'where' || 'which' }} ${{ matrix.tool.command }}
