name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run lint

  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        tool:
          - name: cabal
            command: cabal --version
          - name: ghc
            command: ghc --version
          - name: hls
            command: haskell-language-server-wrapper --version
          - name: stack
            command: stack --version
      fail-fast: false
    runs-on: ${{ matrix.os }}
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: mise plugin link --force ghcup .
      - run: mise install ghcup:${{ matrix.tool.name }}@latest
      - run: mise exec ghcup:${{ matrix.tool.name }}@latest -- ${{ matrix.tool.command }}
